name: Deploy Frontend (Next.js SSR)

on:
  push:
    branches:
      - development
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Clean cache & install deps
      - name: Clean npm cache and lock
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Create .env
      - name: Create .env file
        run: |
          if [ "${{ github.ref }}" == "refs/heads/production" ]; then
            echo "🟢 Production build"
            echo "NEXT_PUBLIC_BASE_URL_API=${{ secrets.NEXT_PUBLIC_BASE_URL_API_PROD }}" >> .env
          else
            echo "🟡 Development build"
            echo "NEXT_PUBLIC_BASE_URL_API=${{ secrets.NEXT_PUBLIC_BASE_URL_API_DEV }}" >> .env
          fi

      # 5. Build project
      - name: Build project
        run: npm run build

      # 6. Test SSH Connection
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: echo "✅ SSH OK"

      # 7. Kirim seluruh project ke server (bukan dist/out, tapi full project)
      - name: Upload project files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "./"
          target: "/tmp/deploy/dev-fe-restaurant"

      # 8. Jalankan deploy script di server
      - name: Run deploy script
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ "${{ github.ref }}" == "refs/heads/production" ]; then
              echo "🟢 Running production deploy script"
              bash /var/www/lms/fe-restaurant-production-deploy.sh
            else
              echo "🟡 Running development deploy script"
              bash /var/www/lms/fe-restaurant-development-deploy.sh
            fi
